# Theme: cobalt2
# By: hoblin

# Main bg
theme[main_bg]="#122738"

# Main text color
theme[main_fg]="#ffffff"

# Title color for boxes
theme[title]="#ffc600"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#80fcff"

# Background color of selected item in processes box
theme[selected_bg]="#0050A4"

# Foreground color of selected item in processes box
theme[selected_fg]="#ffffff"

# Color of inactive/disabled text
theme[inactive_fg]="#aaaaaa"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#80fcff"

# Cpu box outline color
theme[cpu_box]="#0d3a58"

# Memory/disks box outline color
theme[mem_box]="#0d3a58"

# Net up/down box outline color
theme[net_box]="#0d3a58"

# Processes box outline color
theme[proc_box]="#0d3a58"

# Box divider line and small boxes line color
theme[div_line]="#0d3a58"

# Temperature graph colors
theme[temp_start]="#3ad900"
theme[temp_mid]="#ffc600"
theme[temp_end]="#ff628c"

# CPU graph colors
theme[cpu_start]="#0088ff"
theme[cpu_mid]="#80fcff"
theme[cpu_end]="#ffc600"

# Mem/Disk free meter
theme[free_start]="#3ad900"
theme[free_mid]="#ffc600"
theme[free_end]="#ff9d00"

# Mem/Disk cached meter
theme[cached_start]="#80fcff"
theme[cached_mid]="#0088ff"
theme[cached_end]="#fb94ff"

# Mem/Disk available meter
theme[available_start]="#3ad900"
theme[available_mid]="#80fcff"
theme[available_end]="#0088ff"

# Mem/Disk used meter
theme[used_start]="#ffc600"
theme[used_mid]="#ff9d00"
theme[used_end]="#ff628c"

# Download graph colors
theme[download_start]="#3ad900"
theme[download_mid]="#80fcff"
theme[download_end]="#0088ff"

# Upload graph colors
theme[upload_start]="#ffc600"
theme[upload_mid]="#ff9d00"
theme[upload_end]="#ff628c"
